#pragma once
#include"lib_sdl.h"
int score = 0;
int maxScore = 0;
int score_tmp = 0;
bool mode_2 = 0;
const int SCREEN_WIDTH = 1000;
const int SCREEN_HEIGHT = 800;
SDL_Texture* tankTexture = nullptr;
SDL_Texture* enemyTankTexture = nullptr;
SDL_Texture* wallTexture = nullptr;
SDL_Texture* wall2Texture = nullptr;
SDL_Texture* bulletTexture = nullptr;
SDL_Texture* bulletTexture2 = nullptr;
SDL_Texture* backgroundTexture2 = nullptr;
SDL_Texture* backgroundTexture = nullptr;
SDL_Texture* pauseButtonTexture = nullptr;
SDL_Texture* background_multitasking = nullptr;
SDL_Texture* bossTexture = nullptr;
SDL_Texture* supper_bullet_text = nullptr;
SDL_Texture* heart_tex = nullptr;
SDL_Texture* reWall_tex = nullptr;
SDL_Texture* grassTex = nullptr;
SDL_Texture* hs_tex = nullptr;
SDL_Texture* lives1 = nullptr;
SDL_Texture* lives2 = nullptr;
SDL_Texture* lives3 = nullptr;
bool showHelp = false;
SDL_Texture* helpTexture = nullptr;  // Lưu texture của bảng hướng dẫn
Uint32 cooldownStart = 0;  // Thời gian bắt đầu hồi chiêu
Uint32 cooldownTime;  // Thời gian hồi chiêu (ms)
TTF_Font* font = nullptr;
TTF_Font* font2 = nullptr;
SDL_Rect pauseButtonRect = { 850, 30, 80, 80 }; // Kích thước và vị trí nút pause
SDL_Rect multitaskingRect = { 800, 0, 200, 800 };// Kích thước và vị trí phần đa nhiệm 
SDL_Rect Live = { 820, 100, 150, 300 };// Kích thước và vị trí phần mạng
SDL_Rect Live1 = { 880, 240, 90, 180 };// Kích thước và vị trí phần mạng player 1
SDL_Rect rect_p1 = { 820, 300, 75, 75 };// hộp tank 1
SDL_Rect rect_p2 = { 820, 500, 75, 75 };// hộp tank 2
SDL_Rect Live2 = { 880, 440, 90, 180 };// Kích thước và vị trí phần mạng player 2
SDL_Rect hs = { 370, 660, 60, 60 };// Kích thước và vị trí điểm hồi sinh 
Mix_Chunk* explosionSound = nullptr;      // Âm thanh nổ
bool isPaused = false;
bool running = true;
bool gameOver = 0;
bool inMenu = true;
bool played_soundGO = 0;
bool supper_bullet = 0;
SDL_Window* window = nullptr;
SDL_Renderer* renderer = nullptr;
enum Direction { UP, DOWN, LEFT, RIGHT };
